version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://postgres:EL8687NBD8696@postgres:5432/postgres
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  frontend:
    build:
      context: ./FidZen_front
      dockerfile: Dockerfile
    environment:
      - API_URL=http://backend:3000
    ports:
      - "3001:3001"
    depends_on:
      - backend

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: EL8687NBD8696
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
