version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/fidzen_db
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  frontend:
    build:
      context: ./FidZen_front
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - backend

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fidzen_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
